# Generated by Django 2.1.5 on 2019-02-18 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ivataraccount', '0013_auto_20181203_1421'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unconfirmedemail',
            options={'verbose_name': 'unconfirmed email', 'verbose_name_plural': 'unconfirmed emails'},
        ),
    ]
