# Generated by Django 3.0.3 on 2020-02-25 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ivataraccount', '0014_auto_20190218_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='confirmedopenid',
            name='alt_digest1',
            field=models.CharField(blank=True, default=None, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='confirmedopenid',
            name='alt_digest2',
            field=models.CharField(blank=True, default=None, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='confirmedopenid',
            name='alt_digest3',
            field=models.CharField(blank=True, default=None, max_length=64, null=True),
        ),
    ]
