# Generated by Django 3.1.7 on 2021-04-13 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ivataraccount', '0015_auto_20200225_0934'),
    ]

    operations = [
        migrations.AddField(
            model_name='unconfirmedemail',
            name='last_send_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='unconfirmedemail',
            name='last_status',
            field=models.TextField(blank=True, max_length=2047, null=True),
        ),
    ]
