# Generated by Django 2.1.5 on 2019-03-11 10:16

from django.db import migrations
from django.contrib.contenttypes.models import ContentType
from django.contrib.auth.models import Permission
from ivatar.ivataraccount.models import APIKey

def apply_migration(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    (group, created) = Group.objects.get_or_create(name='API-User')
    content_type = ContentType.objects.get_for_model(APIKey)
    (permission, created) = Permission.objects.get_or_create(
      codename='can_use_api',
      name='Can use the API',
      content_type=content_type,
    )


def revert_migration(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Group.objects.get(name='API-User').delete()
    Permission = apps.get_model('auth', 'Permission')
    permission = Permission.objects.get(codename='can_use_api').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('ivataraccount', '0015_apikey'),
    ]

    operations = [
        migrations.RunPython(apply_migration, revert_migration)
    ]
