# Generated by Django 2.1.5 on 2019-03-11 11:03

from django.db import migrations

def apply_migration(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    group = Group.objects.get(name='API-User')
    Permission = apps.get_model('auth', 'Permission')
    permission = Permission.objects.get(codename='can_use_api')
    group.permissions.add(permission)
    group.save()

def revert_migration(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    group = Group.objects.get(name='API-User')
    Permission = apps.get_model('auth', 'Permission')
    permission = Permission.objects.get(codename='can_use_api')
    group.permissions.remove(permission)
    group.save()


class Migration(migrations.Migration):

    dependencies = [
        ('ivataraccount', '0016_auto_20190311_1016'),
    ]

    operations = [
        migrations.RunPython(apply_migration, revert_migration)
    ]
