# -*- coding: utf-8 -*-
# Generated by Django 5.0 on 2024-05-31 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ivataraccount", "0017_auto_20210528_1314"),
    ]

    operations = [
        migrations.AlterField(
            model_name="photo",
            name="format",
            field=models.CharField(max_length=4),
        ),
    ]
