# -*- coding: utf-8 -*-
# Generated by Django 5.1.5 on 2025-01-27 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ivataraccount", "0018_alter_photo_format"),
    ]

    operations = [
        migrations.AddField(
            model_name="confirmedemail",
            name="bluesky_handle",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
