# -*- coding: utf-8 -*-
# Generated by Django 5.1.5 on 2025-01-27 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ivataraccount", "0019_confirmedemail_bluesky_handle"),
    ]

    operations = [
        migrations.AddField(
            model_name="confirmedopenid",
            name="bluesky_handle",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
