fail_fast: true
repos:
-   repo: meta
    hooks:
    -   id: check-useless-excludes
-   repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.0-alpha.4
    hooks:
    -   id: prettier
        files: \.(css|js|md|markdown|json)
-   repo: https://github.com/python/black
    rev: 22.12.0
    hooks:
    -   id: black
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: check-added-large-files
    -   id: check-ast
    -   id: check-case-conflict
    -   id: check-executables-have-shebangs
    -   id: check-json
    -   id: check-merge-conflict
    -   id: check-symlinks
    -   id: check-vcs-permalinks
    -   id: check-xml
    -   id: check-yaml
        args:
        - --unsafe
    -   id: end-of-file-fixer
    -   id: fix-encoding-pragma
    -   id: forbid-new-submodules
    -   id: no-commit-to-branch
        args:
        - --branch
        - gh-pages
    -   id: requirements-txt-fixer
    -   id: sort-simple-yaml
    -   id: trailing-whitespace
-   repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
    -   id: flake8
-   repo: local
    hooks:
    -   id: shfmt
        name: shfmt
        minimum_pre_commit_version: 2.4.0
        language: golang
        additional_dependencies:
        - mvdan.cc/sh/v3/cmd/shfmt@v3.1.1
        entry: shfmt
        args:
        - -w
        - -i
        - '4'
        types:
        - shell
-   repo: https://github.com/asottile/blacken-docs
    rev: v1.12.1
    hooks:
    -   id: blacken-docs
-   repo: https://github.com/hcodes/yaspeller.git
    rev: v8.0.1
    hooks:
    -   id: yaspeller

        types:
        - markdown
-   repo: https://github.com/kadrach/pre-commit-gitlabci-lint
    rev: 22d0495c9894e8b27cc37c2ed5d9a6b46385a44c
    hooks:
    -   id: gitlabci-lint
        args: ["https://git.linux-kernel.at"]
